[package]
name = "pdf-doc"
version = "0.1.0"
edition = "2021"

[dependencies]
google-fonts = { version = "0.1.5" }
heck = "0.5.0"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
skia-safe = { version = "0.75.0", features = ["textlayout"] }
